import fs from 'node:fs';
import path from 'node:path';
import type { AppConfig } from '../../config.js';
import type { CommandRunner } from '../command-runner.js';
import { AppError } from '../../utils/errors.js';
import type { AdapterAvailability, InstanceSpec, RuntimeAdapter, RuntimeLogs, RuntimeStatus } from '../types.js';

function instanceDir(base: string, id: string): string {
  return path.join(base, 'instances', id);
}

function pidFile(base: string, id: string): string {
  return path.join(instanceDir(base, id), 'qemu.pid');
}

function logFile(base: string, id: string): string {
  return path.join(instanceDir(base, id), 'qemu.log');
}

/**
 * QEMU + Android-x86 / Bliss OS driver — the MVP fallback for VPSes that
 * cannot load the redroid binder modules.
 *
 *  - KVM present  -> `-accel kvm` (near-native speed)
 *  - no KVM       -> `-accel tcg` (EXPERIMENTAL — extremely slow and clearly
 *                    surfaced in the availability report)
 *  - no image     -> unavailable; run runtime/scripts/fetch-android-image.sh
 *
 * Disk: the MVP boots a shared base disk image. Per-instance storage
 * isolation (qcow2 overlays) is a documented TODO in docs/ARCHITECTURE.md.
 */
export class QemuAdapter implements RuntimeAdapter {
  readonly id = 'qemu' as const;
  readonly label = 'QEMU + Android-x86 (VM fallback)';

  constructor(
    private readonly config: AppConfig,
    private readonly runner: CommandRunner
  ) {}

  async available(): Promise<AdapterAvailability> {
    const caps = {
      kvm: await this.pathExists('/dev/kvm'),
      binder: false,
      dockerCli: false,
      qemuBinary: false,
      androidImage: await this.pathExists(this.config.QEMU_ANDROID_IMAGE)
    };
    try {
      const res = await this.runner.run({ bin: 'qemu', args: ['--version'], timeoutMs: 10_000 });
      caps.qemuBinary = res.code === 0;
    } catch {
      caps.qemuBinary = false;
    }

    const reasons: string[] = [];
    if (!caps.qemuBinary) reasons.push(`qemu binary not found (${this.config.QEMU_BIN})`);
    if (!caps.androidImage) reasons.push(`android image not present: ${this.config.QEMU_ANDROID_IMAGE}`);

    if (reasons.length > 0) {
      return { available: false, reason: reasons.join('; '), capabilities: caps };
    }
    return {
      available: true,
      reason: caps.kvm
        ? 'QEMU ready with KVM acceleration'
        : 'QEMU ready in TCG (software emulation) mode — EXPERIMENTAL / VERY SLOW without KVM',
      capabilities: caps
    };
  }

  probeAvailable(): Promise<boolean> {
    return this.available().then((a) => a.available);
  }

  async create(spec: InstanceSpec): Promise<void> {
    try {
      await fs.promises.mkdir(instanceDir(this.config.INSTANCES_DIR, spec.id), { recursive: true });
    } catch (err) {
      throw new AppError({ code: 'DRIVER_ERROR', message: `cannot create instance directory: ${(err as Error).message}` });
    }
  }

  async start(spec: InstanceSpec): Promise<void> {
    const avail = await this.available();
    if (!avail.available) {
      throw new AppError({ code: 'RUNTIME_UNAVAILABLE', message: avail.reason });
    }
    const tcg = !avail.capabilities.kvm;

    const adbFwd = spec.adbPort !== null ? `tcp:127.0.0.1:${spec.adbPort}-:5555` : null;
    const args: string[] = [
      '-name',
      `android-vps-${spec.id}`,
      '-pidfile',
      pidFile(this.config.INSTANCES_DIR, spec.id),
      '-machine',
      'q35',
      '-m',
      String(spec.memoryMb),
      '-smp',
      String(spec.cpu),
      '-accel',
      tcg ? 'tcg,thread=multi' : 'kvm',
      '-drive',
      `file=${this.config.QEMU_ANDROID_IMAGE},format=raw,if=virtio`,
      '-device',
      'e1000,netdev=net0',
      '-netdev',
      adbFwd ? `user,id=net0,${adbFwd}` : 'user,id=net0',
      '-display',
      'none',
      '-vnc',
      `127.0.0.1:${spec.vncPort}`,
      '-k',
      'en-us',
      '-daemonize'
    ];

    const workDir = instanceDir(this.config.INSTANCES_DIR, spec.id);
    await fs.promises.mkdir(workDir, { recursive: true });

    // Rendering aid for operators — never executed by the API (shell: false everywhere).
    const bootScript = path.join(workDir, 'boot.sh');
    await fs.promises.writeFile(
      bootScript,
      `#!/bin/bash\n# generated by QemuAdapter — for manual debugging only\n${this.config.QEMU_BIN} \\\n  ` +
        args.map((a) => `'${a.replace(/'/g, `'\\''`)}'`).join(' \\\n  ') +
        '\n',
      'utf8'
    );

    const logPath = logFile(this.config.INSTANCES_DIR, spec.id);
    try {
      await fs.promises.mkdir(path.dirname(logPath), { recursive: true });
      await fs.promises.appendFile(logPath, `-- boot request ${new Date().toISOString()} --\n`);
    } catch {
      /* best effort */
    }

    const res = await this.runner.run({ bin: 'qemu', args, timeoutMs: 30_000 });
    if (res.code !== 0) {
      throw new AppError({
        code: 'DRIVER_ERROR',
        message: `qemu failed to start: ${res.stderr.trim() || res.stdout.trim()}`
      });
    }
  }

  async stop(spec: InstanceSpec): Promise<void> {
    const pid = await this.readPid(spec.id);
    if (pid === null) return;
    const res = await this.runner.run({ bin: 'kill', args: ['-TERM', String(pid)] });
    if (res.code !== 0 && !res.stderr.includes('No such process')) {
      throw new AppError({ code: 'DRIVER_ERROR', message: `could not terminate qemu: ${res.stderr.trim()}` });
    }
    await this.waitForExit(spec.id, 15_000);
  }

  async destroy(spec: InstanceSpec): Promise<void> {
    await this.stop(spec);
    try {
      await fs.promises.rm(instanceDir(this.config.INSTANCES_DIR, spec.id), { recursive: true, force: true });
    } catch {
      /* best effort */
    }
  }

  async status(spec: InstanceSpec): Promise<RuntimeStatus> {
    const pid = await this.readPid(spec.id);
    if (pid === null) return { kind: 'stopped' };
    const alive = await this.runner.run({ bin: 'kill', args: ['-0', String(pid)] });
    if (alive.code === 0) {
      return { kind: 'running', pid, uptimeSeconds: null, vncPort: spec.vncPort };
    }
    return { kind: 'stopped' };
  }

  async logs(spec: InstanceSpec, lines: number): Promise<RuntimeLogs> {
    const logPath = logFile(this.config.INSTANCES_DIR, spec.id);
    if (!(await this.pathExists(logPath))) {
      return { text: '(no logs — instance has not been booted yet)\n' };
    }
    const res = await this.runner.run({ bin: 'tail', args: ['-n', String(lines), logPath] });
    return { text: (res.stdout || res.stderr) + '\n' };
  }

  private async readPid(id: string): Promise<number | null> {
    try {
      const content = (await fs.promises.readFile(pidFile(this.config.INSTANCES_DIR, id), 'utf8')).trim();
      const pid = Number(content);
      return Number.isInteger(pid) && pid > 0 ? pid : null;
    } catch {
      return null;
    }
  }

  private async waitForExit(id: string, timeoutMs: number): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
      const pid = await this.readPid(id);
      if (pid === null) return;
      const alive = await this.runner.run({ bin: 'kill', args: ['-0', String(pid)] });
      if (alive.code !== 0) return;
      await new Promise((r) => setTimeout(r, 500));
    }
    const pid = await this.readPid(id);
    if (pid !== null) {
      await this.runner.run({ bin: 'kill', args: ['-KILL', String(pid)] });
    }
  }

  private async pathExists(p: string): Promise<boolean> {
    try {
      await fs.promises.access(p);
      return true;
    } catch {
      return false;
    }
  }
}